### ISSUE TITLE
README.md中安装是错误的

### ISSUE THREAD

**Issue by hulang** [yzh52521/think-geoip#1]
`composer require yzh52521/geoip`
应该是：
`composer require yzh52521/think-geoip`

README.md里面尽量中文说明吧。。config/geoip.php 里面的注释，全是英文的，我都看不懂额。。。
我自己写示例：
$ip = '219.138.184.118';
$arr = geoip($ip);
打印：$arr，是空的。。是我哪里搞错了吗？

**Comment by yuanzhihai** [comment]
README.md 已修复

```
$ip = '219.138.184.118';
$arr = geoip($ip);
 打印 返回以下数据
yzh52521\GeoIP\Location {#152 ▼
  #attributes: array:14 [▼
    "ip" => "219.138.184.118"
    "iso_code" => "CN"
    "country" => "China"
    "city" => "Wuhan"
    "state" => "HB"
    "state_name" => "Hubei"
    "postal_code" => ""
    "lat" => 30.6155
    "lon" => 114.255
    "timezone" => "Asia/Shanghai"
    "continent" => "AS"
    "currency" => "CNY"
    "default" => false
    "cached" => true
  ]
}
```

**Comment by hulang** [comment]
@yzh52521 怎么获取里面的数据呢。。README.md和config/geoip.php，能不能中文啊。。

**Comment by yuanzhihai** [comment]
> @yzh52521 怎么获取里面的数据呢。。README.md和config/geoip.php，能不能中文啊。。

返回数组  怎么获取不用多说吧，
